server:
  port: 80

spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  datasource:
    #数据库文件在resource/sql那里
    url: jdbc:mysql://47.100.45.101:3306/file_db?serverTimezone=Asia/Shanghai&useAffectedRows=true&useSSL=true&characterEncoding=utf8
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1200000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhifa.bigfileupload.domain


